global_costmap:
    footprint: [[0.325,0.225],[0.325,-0.225],[-0.325,-0.225],[-0.325,0.225]] 
    footprint_padding: 0.01
    transform_tolerance: 1.0
    update_frequency: 1.0
    publish_frequency: 5.0
    rolling_window: false

    global_frame: map
    robot_base_frame: base_link
    resolution: 0.05

    rolling_window: false
    track_unknown_space: true


    plugins: 
        - {name: static,    type: "costmap_2d::StaticLayer"}            
        - {name: inflation, type: "costmap_2d::InflationLayer"}

    static:        
        map_topic: /map 
        subscribe_to_updates: true

    sensor:
        observation_sources: laser_scan_sensor
        laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

    inflation:
        inflation_radius: 0.2  #0.23
        cost_scaling_factor: 5.0     #5.0
# global_costmap:
#   global_frame: map
#   robot_base_frame: base_link
#   update_frequency: 1.0
#   publish_frequency: 0.5
#   static_map: true
 
#   transform_tolerance: 0.5
#   plugins:
#     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
#     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
#     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}