// Generated by gencpp from file qingzhou_locate/RobotLocationResponse.msg
// DO NOT EDIT!


#ifndef QINGZHOU_LOCATE_MESSAGE_ROBOTLOCATIONRESPONSE_H
#define QINGZHOU_LOCATE_MESSAGE_ROBOTLOCATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qingzhou_locate
{
template <class ContainerAllocator>
struct RobotLocationResponse_
{
  typedef RobotLocationResponse_<ContainerAllocator> Type;

  RobotLocationResponse_()
    : location(0)  {
    }
  RobotLocationResponse_(const ContainerAllocator& _alloc)
    : location(0)  {
  (void)_alloc;
    }



   typedef int32_t _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotLocationResponse_

typedef ::qingzhou_locate::RobotLocationResponse_<std::allocator<void> > RobotLocationResponse;

typedef boost::shared_ptr< ::qingzhou_locate::RobotLocationResponse > RobotLocationResponsePtr;
typedef boost::shared_ptr< ::qingzhou_locate::RobotLocationResponse const> RobotLocationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator1> & lhs, const ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator1> & lhs, const ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qingzhou_locate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ee1757f0484d31829b2fbdfc3bd23cd";
  }

  static const char* value(const ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ee1757f0484d318ULL;
  static const uint64_t static_value2 = 0x29b2fbdfc3bd23cdULL;
};

template<class ContainerAllocator>
struct DataType< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qingzhou_locate/RobotLocationResponse";
  }

  static const char* value(const ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 location\n"
;
  }

  static const char* value(const ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotLocationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qingzhou_locate::RobotLocationResponse_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    Printer<int32_t>::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QINGZHOU_LOCATE_MESSAGE_ROBOTLOCATIONRESPONSE_H
