// Generated by gencpp from file qingzhou_locate/RobotLocationRequest.msg
// DO NOT EDIT!


#ifndef QINGZHOU_LOCATE_MESSAGE_ROBOTLOCATIONREQUEST_H
#define QINGZHOU_LOCATE_MESSAGE_ROBOTLOCATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qingzhou_locate
{
template <class ContainerAllocator>
struct RobotLocationRequest_
{
  typedef RobotLocationRequest_<ContainerAllocator> Type;

  RobotLocationRequest_()
    {
    }
  RobotLocationRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotLocationRequest_

typedef ::qingzhou_locate::RobotLocationRequest_<std::allocator<void> > RobotLocationRequest;

typedef boost::shared_ptr< ::qingzhou_locate::RobotLocationRequest > RobotLocationRequestPtr;
typedef boost::shared_ptr< ::qingzhou_locate::RobotLocationRequest const> RobotLocationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace qingzhou_locate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qingzhou_locate/RobotLocationRequest";
  }

  static const char* value(const ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotLocationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::qingzhou_locate::RobotLocationRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // QINGZHOU_LOCATE_MESSAGE_ROBOTLOCATIONREQUEST_H
