#map_type: voxel
#map_type: costmap

#footprint: [[0.23,0.19],[0.25,0],[0.23,-0.19],[-0.23, -0.19],[-0.23,0.19]]
# footprint_padding : 
footprint: [[0.23,0.12],[0.25,0],[0.23,-0.12],[-0.23, -0.12],[-0.23,0.12]]
cost_scaling_factor: 15
recovery_behavior_enabled: True
controller_frequency: 5

obstacle_layer:
  enabled: true
  combination_method:   1
  track_unknown_space:  false
  origin_z: 0.0
  z_voxels: 20
  z_resolution: 0.1
  unknown_cost_value: 0
  unknown_threshold: 8
  mark_threshold: 0
  publish_voxel_map: false

  obstacle_range: 6.0
  raytrace_range: 7.0
  #footprint: [[-0.3,-0.4],[-0.3,1.03],[-0.0,1.03],[0.3, 1.03],[0.3,-0.4]]
  #robot_radius: 0.25
  #inflation_radius: 1.0 
  #inf_is_valid: true
  max_obstacle_height: 0.40
  min_obstacle_height: 0.03
  controller_frequency: 5
  observation_sources: scan 
  #point_cloud_sensor

  scan: {sensor_frame: base_link,  observation_persistence: 0.0, 
  max_obstacle_height: 0.3, min_obstacle_height: 0.05, data_type: LaserScan, topic: /scan, 
  marking: true,clearing: true}

inflation_layer:
 enabled:              true
 cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
 inflation_radius:     0.35  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
 enabled: true

