#local_costmap:
#  global_frame: map
#  robot_base_frame: base_link  #base_footprint
#  update_frequency: 5.0
#  publish_frequency: 2.0
#  static_map: false
#  rolling_window: true
#  width: 10  #5
#  height: 10  #5
#  resolution: 0.05
#  transform_tolerance: 0.5
#  cost_scaling_factor: 5
#  inflation_radius: 0.15 #0.25


local_costmap:
   global_frame: odom  #参数定义了代价地图应该运行的坐标系
   robot_base_frame: base_link #参数定义了代价地图应该为机器人的基座的坐标系。
   update_frequency: 4.0 #参数决定了代价地图更新的频率（以Hz为单位）。
   publish_frequency: 3.0   #3Hz 2hz参数决定代价地图发布可视化信息的速率（以Hz为单位）。
   #static_map: false #参数确定是否由map_server提供的地图服务来进行代价地图的初始化。
   rolling_window: true  #参数设置为true意味着当机器人移动时，保持机器人在本地代价地图中心。
   width: 4 #代价地图宽度4.0
   height: 4 #代价地图高度4.0
   resolution: 0.05  #0.05代价地图分辨率（米/单元格）
   transform_tolerance: 1.0 #0.5
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}        

   #obstacle_layer:         
   #   observation_sources: scan         
   #   scan: {date_type: LaserScan, topic: /scan, making: true, clearing: true, expected_update_rate: 0}
   #inflation_layer:
   #      inflation_radius: 0.1
 