controller_frequency: 20
recovery_behavior_enabled: false
clearing_rotation_allowed: false

planner_frequency : 5.0

TrajectoryPlannerROS:
   max_vel_x: 15
   min_vel_x: 0.0
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 50
   min_vel_theta: -1
   min_in_place_vel_theta: 0.5
   escape_vel: -0.4
   acc_lim_x: 7
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 50

   holonomic_robot: false
   yaw_goal_tolerance: 0.2 # about 6 degrees
   xy_goal_tolerance: 0.2  # 10 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 1.5
   gdist_scale: 0.6
   meter_scoring: true

   heading_lookahead: 0.5 #0.5
   heading_scoring: false
   heading_scoring_timestep: 0.5
   occdist_scale: 0.4
   oscillation_reset_dist: 0.01
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.2
   sim_granularity: 0.01
   angular_sim_granularity: 0.01
   vx_samples: 15
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false
