local_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 10.0
   publish_frequency: 6.0
   static_map: true
   rolling_window: false
   width: 6.0
   height: 6.0
   resolution: 0.02
   transform_tolerance: 1.0
   footprint : [[0.325,0.225],[0.325,-0.225],[-0.325,-0.225],[-0.325,0.225]]
   footprint_padding : 0.01

   # plugins:            
   # - {name: sensor,    type: "costmap_2d::ObstacleLayer"}
   # - {name: inflation, type: "costmap_2d::InflationLayer"}
   # - {name: static_layer,        type: "costmap_2d::StaticLayer"}