local_costmap:
    footprint: [[0.325,0.225],[0.325,-0.225],[-0.325,-0.225],[-0.325,0.225]] 
    footprint_padding: 0.01
    transform_tolerance: 1.0
    update_frequency: 3.0
    publish_frequency: 1.0

    global_frame: map
    robot_base_frame: base_link
    #static_map: false #true
    rolling_window: true
    width: 2.0
    height: 2.0
    resolution: 0.1    #0.05

    plugins:            
        - {name: sensor,    type: "costmap_2d::ObstacleLayer"}
        - {name: inflation, type: "costmap_2d::InflationLayer"}

        #"inflation_layer"一般放在最后面。因为它最终将前面几个层的障碍物信息一起膨胀。如果不想膨胀某个插件层，则可以将其放在"inflation_layer"之后

    sensor:
        observation_sources: laser_scan_sensor
        laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

    inflation:
        inflation_radius: 1.5
        cost_scaling_factor: 8.0
